/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

public class Rectangle {
    //Declaring Variables
    private int x;
    private int y;
    private int width;
    private int height;
    //Rectangle Constructor for Customization! (With Parameters!)
    public Rectangle(int x, int y, int width, int height) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
    //Rectangle Constructor for Default settings!
    public Rectangle() {
        this(0,0,1,1);
    }
    //Getters for the private variables!
    public int getX() { return x; }
    public int getY() { return y; }
    public int getWidth() { return width; }
    public int getHeight() { return height; }
    //Setters for the private variables!
    public void setX(int updated_x) {
        this.x = updated_x;
    }
    public void setY(int updated_y) {
        this.y = updated_y;
    }
    public void setWidth(int updated_Width) throws IllegalArgumentException{
        if(updated_Width <= 0) {
            throw new IllegalArgumentException();
        }
        this.width = updated_Width;
    }
    public void setHeight(int updated_Height) {
        if(updated_Height<= 0) {
            throw new IllegalArgumentException();
        }
        this.height = updated_Height;
    }

    //Additional Methods to fulfill requirements
    public boolean equal(Rectangle r) {
        return this.x == r.getX() && this.y == r.getY() && this.width == r.getWidth() && this.height == r.getHeight();
    }
    public int area() {
        return this.width * this.height;
    }
    //If the rectangle r even touches the boundary of the main rectangle, test fails!
    public boolean contains(Rectangle r) {
        return this.x < r.getX() && this.y > r.getY() && (this.x + this.width) > (r.getX() + r.getWidth()) && (this.y + this.height) > (r.getY() + r.getHeight());
    }
}